// <auto-generated />
using System;
using ClinicFlowAi.Infrastructure.Postgres.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClinicFlowAi.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(ClinicFlowDbContext))]
    partial class ClinicFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClinicFlowAi.Infrastructure.Postgres.Persistence.AppointmentSlotEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AppointmentTypeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClinicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClinicianId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClinicianId", "StartsAtUtc");

                    b.ToTable("appointment_slots", (string)null);
                });

            modelBuilder.Entity("ClinicFlowAi.Infrastructure.Postgres.Persistence.AuditEventEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("ClinicFlowAi.Infrastructure.Postgres.Persistence.BookingEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatientReferenceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SlotId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SlotId")
                        .IsUnique();

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("ClinicFlowAi.Infrastructure.Postgres.Persistence.ClinicianEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ClinicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("clinicians", (string)null);
                });

            modelBuilder.Entity("ClinicFlowAi.Infrastructure.Postgres.Persistence.ScheduleRuleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ClinicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClinicianId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClinicianId");

                    b.ToTable("schedule_rules", (string)null);
                });

            modelBuilder.Entity("ClinicFlowAi.Infrastructure.Postgres.Persistence.AppointmentSlotEntity", b =>
                {
                    b.HasOne("ClinicFlowAi.Infrastructure.Postgres.Persistence.ClinicianEntity", "Clinician")
                        .WithMany("AppointmentSlots")
                        .HasForeignKey("ClinicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinician");
                });

            modelBuilder.Entity("ClinicFlowAi.Infrastructure.Postgres.Persistence.BookingEntity", b =>
                {
                    b.HasOne("ClinicFlowAi.Infrastructure.Postgres.Persistence.AppointmentSlotEntity", "Slot")
                        .WithOne("Booking")
                        .HasForeignKey("ClinicFlowAi.Infrastructure.Postgres.Persistence.BookingEntity", "SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("ClinicFlowAi.Infrastructure.Postgres.Persistence.ScheduleRuleEntity", b =>
                {
                    b.HasOne("ClinicFlowAi.Infrastructure.Postgres.Persistence.ClinicianEntity", "Clinician")
                        .WithMany("ScheduleRules")
                        .HasForeignKey("ClinicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinician");
                });

            modelBuilder.Entity("ClinicFlowAi.Infrastructure.Postgres.Persistence.AppointmentSlotEntity", b =>
                {
                    b.Navigation("Booking");
                });

            modelBuilder.Entity("ClinicFlowAi.Infrastructure.Postgres.Persistence.ClinicianEntity", b =>
                {
                    b.Navigation("AppointmentSlots");

                    b.Navigation("ScheduleRules");
                });
#pragma warning restore 612, 618
        }
    }
}
